
[functions.exercise-search]
enabled = true
verify_jwt = true
import_map = "./functions/exercise-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/exercise-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/exercise-search/*.html" ]

[functions.ai-complete]
enabled = true
verify_jwt = false
entrypoint = "./functions/ai-complete/index.ts"
